modLoader="javafml"
loaderVersion="[38,)"
issueTrackerURL="https://github.com/OreCruncher/DynamicSurroundings/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/dynamic-surroundings"
logoFile="logo.png"
license = "GPL-3.0"
showAsResourcePack=false

[[mods]]
	modId="dsurround"
	version="${version}"
	displayName="§3Dynamic Surroundings"
	updateJSONURL=""
	credits=""
	authors=""
	description=""

	[[dependencies.dsurround]]
		modId="forge"
		mandatory=true
		versionRange="[36.2.0,)"
		ordering="NONE"
		side="CLIENT"

	[[dependencies.dsurround]]
		modId="minecraft"
		mandatory=true
		versionRange="[1.18,)"
		ordering="NONE"
		side="CLIENT"

[[mods]]
	modId="sndctrl"
	version="${version}"
	displayName="§3Dynamic Surroundings: §eSound Control"
	credits="§6All the Players§r that installed and enjoyed §2Dynamic Surroundings§r§6SonicEther§r for making §2SoundPhysics§r GPL3"
	authors="§6OreCruncher§r"
	description="Enhances and gives the player §6control§r over their §2Minecraft§r §6sound experience§r."

	[[dependencies.sndctrl]]
		modId="dsurround"
		mandatory=false
		versionRange="[1.18,)"
		ordering="AFTER"
		side="CLIENT"
	
[[mods]]
	modId="environs"
	version="${version}"
	displayName="§3Dynamic Surroundings: §eEnvirons"
	credits="§6All the Players§r that installed and enjoyed §2Dynamic Surroundings§r"
	authors="§6OreCruncher§r"
	description="Adds §6sound§r and §6visual§r effects to §6biomes§r"
	
	[[dependencies.environs]]
		modId="sndctrl"
		mandatory=false
		versionRange="[1.18,)"
		ordering="AFTER"
		side="CLIENT"

[[mods]]
	modId="mobeffects"
	version="${version}"
	displayName="§3Dynamic Surroundings: §eMob Effects"
	credits="§6All the Players§r that installed and enjoyed §2Dynamic Surroundings§r"
	authors="§6OreCruncher§r"
	description="Giving §6mobs§r and §6players§r special §6sound§r and §6visual§r effects."
	
	[[dependencies.mobeffects]]
		modId="sndctrl"
		mandatory=false
		versionRange="[1.18,)"
		ordering="AFTER"
		side="CLIENT"